"""Demo fixtures and canned topologies for Upstream Discovery."""

from __future__ import annotations

from .models import Hop, PortDiagnostics, UpstreamPath

# Canned multi-hop upstream chain for demo mode
DEMO_HOPS: list[Hop] = [
    Hop(
        hop_index=1,
        hostname="Access-SW2",
        mgmt_ip="10.0.0.3",
        sys_descr="Cisco IOS Software, C2960L Software (C2960L-UNIVERSALK9-M), Version 15.2(7)E",
        platform="cisco WS-C2960L-24TS-LL",
        device_type="switch",
        is_stp_root=False,
        stp_root_bridge_id="32768 / 00:1a:2b:3c:4d:5e",
        stp_bridge_id="32768 / aa:bb:cc:00:11:22",
        stp_root_port_num=24,
        default_gateway="10.0.0.1",
        status="ok",
        response_time_ms=4.2,
        ports=[
            PortDiagnostics(
                port_id=1,
                port_name="Gi1/0/1",
                pvid=200,
                allowed_vlans=[200],
                stp_state="forwarding",
                link_speed_mbps=1000,
                is_downlink=True,
                neighbor_name="Local-Host",
                neighbor_ip="10.0.0.42",
                neighbor_port="eth0",
            ),
            PortDiagnostics(
                port_id=2,
                port_name="Gi1/0/2",
                pvid=200,
                allowed_vlans=[200],
                stp_state="disabled",
                link_speed_mbps=None,
            ),
            PortDiagnostics(
                port_id=23,
                port_name="Gi1/0/23",
                pvid=100,
                allowed_vlans=[100, 200],
                stp_state="blocking",
                link_speed_mbps=100,
            ),
            PortDiagnostics(
                port_id=24,
                port_name="Gi1/0/24",
                pvid=100,
                allowed_vlans=[100, 200, 300],
                stp_state="forwarding",
                link_speed_mbps=1000,
                is_root_port=True,
                is_uplink=True,
                neighbor_name="Core-SW1",
                neighbor_ip="10.0.0.2",
                neighbor_port="Gi0/24",
            ),
        ],
        uplink_port=PortDiagnostics(
            port_id=24,
            port_name="Gi1/0/24",
            pvid=100,
            allowed_vlans=[100, 200, 300],
            stp_state="forwarding",
            link_speed_mbps=1000,
            is_root_port=True,
            is_uplink=True,
            neighbor_name="Core-SW1",
            neighbor_ip="10.0.0.2",
            neighbor_port="Gi0/24",
        ),
        downlink_port=PortDiagnostics(
            port_id=1,
            port_name="Gi1/0/1",
            pvid=200,
            allowed_vlans=[200],
            stp_state="forwarding",
            link_speed_mbps=1000,
            is_downlink=True,
            neighbor_name="Local-Host",
            neighbor_ip="10.0.0.42",
            neighbor_port="eth0",
        ),
    ),
    Hop(
        hop_index=2,
        hostname="Core-SW1",
        mgmt_ip="10.0.0.2",
        sys_descr="Cisco IOS Software, C2960X Software (C2960X-UNIVERSALK9-M), Version 15.2(7)E",
        platform="cisco WS-C2960X-24TS-L",
        device_type="switch",
        is_stp_root=True,
        stp_root_bridge_id="32768 / 00:1a:2b:3c:4d:5e",
        stp_bridge_id="32768 / 00:1a:2b:3c:4d:5e",
        stp_root_port_num=0,
        default_gateway="10.0.0.1",
        status="root_reached",
        response_time_ms=3.8,
        ports=[
            PortDiagnostics(
                port_id=1,
                port_name="Gi0/1",
                pvid=100,
                allowed_vlans=[100, 200, 300],
                stp_state="forwarding",
                link_speed_mbps=1000,
                is_uplink=True,
                neighbor_name="FW-Edge01",
                neighbor_ip="10.0.0.1",
                neighbor_port="port1",
            ),
            PortDiagnostics(
                port_id=24,
                port_name="Gi0/24",
                pvid=100,
                allowed_vlans=[100, 200, 300],
                stp_state="forwarding",
                link_speed_mbps=1000,
                is_downlink=True,
                neighbor_name="Access-SW2",
                neighbor_ip="10.0.0.3",
                neighbor_port="Gi1/0/24",
            ),
        ],
        uplink_port=PortDiagnostics(
            port_id=1,
            port_name="Gi0/1",
            pvid=100,
            allowed_vlans=[100, 200, 300],
            stp_state="forwarding",
            link_speed_mbps=1000,
            is_uplink=True,
            neighbor_name="FW-Edge01",
            neighbor_ip="10.0.0.1",
            neighbor_port="port1",
        ),
        downlink_port=PortDiagnostics(
            port_id=24,
            port_name="Gi0/24",
            pvid=100,
            allowed_vlans=[100, 200, 300],
            stp_state="forwarding",
            link_speed_mbps=1000,
            is_downlink=True,
            neighbor_name="Access-SW2",
            neighbor_ip="10.0.0.3",
            neighbor_port="Gi1/0/24",
        ),
    ),
    Hop(
        hop_index=3,
        hostname="FW-Edge01",
        mgmt_ip="10.0.0.1",
        sys_descr="FortiGate-60F v7.2.5,build1517,230612 (GA.M)",
        platform="Fortinet FortiGate 60F",
        device_type="firewall",
        is_stp_root=False,
        default_gateway="203.0.113.1",
        status="router_reached",
        response_time_ms=2.1,
        isp_gateway="203.0.113.1",
        wan_interface=PortDiagnostics(
            port_id=1,
            port_name="wan1",
            link_speed_mbps=1000,
            stp_state="unknown",
            oper_status="up",
            admin_status="up",
            is_uplink=True,
            neighbor_name="ISP Gateway",
            neighbor_ip="203.0.113.1",
        ),
        lan_interface=PortDiagnostics(
            port_id=2,
            port_name="lan",
            link_speed_mbps=1000,
            stp_state="unknown",
            oper_status="up",
            admin_status="up",
            is_downlink=True,
            neighbor_name="Core-SW1",
            neighbor_ip="10.0.0.2",
            neighbor_port="Gi0/1",
        ),
        ports=[
            PortDiagnostics(
                port_id=1,
                port_name="wan1",
                link_speed_mbps=1000,
                stp_state="unknown",
                oper_status="up",
                admin_status="up",
                is_uplink=True,
                neighbor_name="ISP Gateway",
                neighbor_ip="203.0.113.1",
            ),
            PortDiagnostics(
                port_id=2,
                port_name="lan",
                link_speed_mbps=1000,
                stp_state="unknown",
                oper_status="up",
                admin_status="up",
                is_downlink=True,
                neighbor_name="Core-SW1",
                neighbor_ip="10.0.0.2",
                neighbor_port="Gi0/1",
            ),
            PortDiagnostics(
                port_id=3,
                port_name="dmz",
                link_speed_mbps=None,
                stp_state="unknown",
                oper_status="down",
                admin_status="down",
            ),
            PortDiagnostics(
                port_id=4,
                port_name="ssl.root",
                link_speed_mbps=None,
                stp_state="unknown",
                oper_status="up",
                admin_status="up",
            ),
        ],
        uplink_port=PortDiagnostics(
            port_id=1,
            port_name="wan1",
            link_speed_mbps=1000,
            stp_state="unknown",
            oper_status="up",
            admin_status="up",
            is_uplink=True,
            neighbor_name="ISP Gateway",
            neighbor_ip="203.0.113.1",
        ),
        downlink_port=PortDiagnostics(
            port_id=2,
            port_name="lan",
            link_speed_mbps=1000,
            stp_state="unknown",
            oper_status="up",
            admin_status="up",
            is_downlink=True,
            neighbor_name="Core-SW1",
            neighbor_ip="10.0.0.2",
            neighbor_port="Gi0/1",
        ),
    ),
]


def get_demo_path(start_ip: str = "10.0.0.3") -> UpstreamPath:
    """Return a canned demo upstream path."""
    return UpstreamPath(
        start_ip=start_ip,
        hops=DEMO_HOPS,
        edge_type="firewall",
        edge_summary="Edge firewall reached: FW-Edge01 (10.0.0.1) — WAN wan1 via ISP gateway 203.0.113.1",
        success=True,
    )
