"""Demo fixtures and canned topologies for Upstream Discovery."""

from __future__ import annotations

from .models import Hop, PortDiagnostics, UpstreamPath
from .walker import (
    OID_SYS_DESCR,
    OID_SYS_OBJECT_ID,
    OID_SYS_NAME,
    OID_IF_NAME,
    OID_IF_HIGH_SPEED,
    OID_IF_OPER_STATUS,
    OID_IF_ADMIN_STATUS,
    OID_LLDP_REM_SYS_NAME,
    OID_LLDP_REM_PORT_ID,
    OID_LLDP_REM_MAN_ADDR_TABLE,
    OID_IP_ROUTE_NEXT_HOP_DEFAULT,
    OID_IP_ROUTE_IF_INDEX_DEFAULT,
    OID_IP_NET_TO_MEDIA_TABLE,
    OID_DOT1D_BASE_BRIDGE_ADDRESS,
    OID_DOT1D_STP_ROOT_BRIDGE,
    OID_DOT1D_STP_ROOT_PORT,
    OID_DOT1D_BASE_PORT_IFINDEX,
    OID_DOT1D_STP_PORT_STATE,
    OID_DOT1Q_PVID,
    OID_DOT1Q_VLAN_STATIC_EGRESS_PORTS,
    OID_DOT1Q_VLAN_CURRENT_EGRESS_PORTS,
    OID_DOT1Q_VLAN_STATIC_UNTAGGED_PORTS,
    OID_DOT1Q_VLAN_CURRENT_UNTAGGED_PORTS,
)

# Canned multi-hop upstream chain for demo mode
DEMO_HOPS: list[Hop] = [
    Hop(
        hop_index=1,
        hostname="Access-SW2",
        mgmt_ip="10.0.0.3",
        sys_descr="Cisco IOS Software, C2960L Software (C2960L-UNIVERSALK9-M), Version 15.2(7)E",
        platform="cisco WS-C2960L-24TS-LL",
        device_type="switch",
        is_stp_root=False,
        stp_root_bridge_id="32768 / 00:1a:2b:3c:4d:5e",
        stp_bridge_id="32768 / aa:bb:cc:00:11:22",
        stp_root_port_num=24,
        default_gateway="10.0.0.1",
        status="ok",
        response_time_ms=4.2,
        ports=[
            PortDiagnostics(
                port_id=3,
                port_name="Port 3",
                pvid=1,
                allowed_vlans=[1, 30],
                tagged_vlans=[30],
                untagged_vlans=[1],
                stp_state="forwarding",
                link_speed_mbps=1000,
                is_downlink=True,
                neighbor_name="Local-Host",
                neighbor_ip="10.0.0.42",
                neighbor_port="eth0",
            ),
            PortDiagnostics(
                port_id=2,
                port_name="Gi1/0/2",
                pvid=200,
                allowed_vlans=[200],
                stp_state="disabled",
                link_speed_mbps=None,
            ),
            PortDiagnostics(
                port_id=23,
                port_name="Gi1/0/23",
                pvid=100,
                allowed_vlans=[100, 200],
                stp_state="blocking",
                link_speed_mbps=100,
            ),
            PortDiagnostics(
                port_id=24,
                port_name="Gi1/0/24",
                pvid=100,
                allowed_vlans=[100, 200, 300],
                tagged_vlans=[200, 300],
                untagged_vlans=[100],
                stp_state="forwarding",
                link_speed_mbps=1000,
                is_root_port=True,
                is_uplink=True,
                neighbor_name="Core-SW1",
                neighbor_ip="10.0.0.2",
                neighbor_port="Gi0/24",
            ),
        ],
        uplink_port=PortDiagnostics(
            port_id=24,
            port_name="Gi1/0/24",
            pvid=100,
            allowed_vlans=[100, 200, 300],
            tagged_vlans=[200, 300],
            untagged_vlans=[100],
            stp_state="forwarding",
            link_speed_mbps=1000,
            is_root_port=True,
            is_uplink=True,
            neighbor_name="Core-SW1",
            neighbor_ip="10.0.0.2",
            neighbor_port="Gi0/24",
        ),
        downlink_port=PortDiagnostics(
            port_id=3,
            port_name="Port 3",
            pvid=1,
            allowed_vlans=[1, 30],
            tagged_vlans=[30],
            untagged_vlans=[1],
            stp_state="forwarding",
            link_speed_mbps=1000,
            is_downlink=True,
            neighbor_name="Local-Host",
            neighbor_ip="10.0.0.42",
            neighbor_port="eth0",
        ),
    ),
    Hop(
        hop_index=2,
        hostname="Core-SW1",
        mgmt_ip="10.0.0.2",
        sys_descr="Cisco IOS Software, C2960X Software (C2960X-UNIVERSALK9-M), Version 15.2(7)E",
        platform="cisco WS-C2960X-24TS-L",
        device_type="switch",
        is_stp_root=True,
        stp_root_bridge_id="32768 / 00:1a:2b:3c:4d:5e",
        stp_bridge_id="32768 / 00:1a:2b:3c:4d:5e",
        stp_root_port_num=0,
        default_gateway="10.0.0.1",
        status="root_reached",
        response_time_ms=3.8,
        ports=[
            PortDiagnostics(
                port_id=1,
                port_name="Gi0/1",
                pvid=100,
                allowed_vlans=[100, 200, 300],
                stp_state="forwarding",
                link_speed_mbps=1000,
                is_uplink=True,
                neighbor_name="FW-Edge01",
                neighbor_ip="10.0.0.1",
                neighbor_port="port1",
            ),
            PortDiagnostics(
                port_id=24,
                port_name="Gi0/24",
                pvid=100,
                allowed_vlans=[100, 200, 300],
                stp_state="forwarding",
                link_speed_mbps=1000,
                is_downlink=True,
                neighbor_name="Access-SW2",
                neighbor_ip="10.0.0.3",
                neighbor_port="Gi1/0/24",
            ),
        ],
        uplink_port=PortDiagnostics(
            port_id=1,
            port_name="Gi0/1",
            pvid=100,
            allowed_vlans=[100, 200, 300],
            stp_state="forwarding",
            link_speed_mbps=1000,
            is_uplink=True,
            neighbor_name="FW-Edge01",
            neighbor_ip="10.0.0.1",
            neighbor_port="port1",
        ),
        downlink_port=PortDiagnostics(
            port_id=24,
            port_name="Gi0/24",
            pvid=100,
            allowed_vlans=[100, 200, 300],
            stp_state="forwarding",
            link_speed_mbps=1000,
            is_downlink=True,
            neighbor_name="Access-SW2",
            neighbor_ip="10.0.0.3",
            neighbor_port="Gi1/0/24",
        ),
    ),
    Hop(
        hop_index=3,
        hostname="FW-Edge01",
        mgmt_ip="10.0.0.1",
        sys_descr="FortiGate-60F v7.2.5,build1517,230612 (GA.M)",
        platform="Fortinet FortiGate 60F",
        device_type="firewall",
        is_stp_root=False,
        default_gateway="203.0.113.1",
        status="router_reached",
        response_time_ms=2.1,
        isp_gateway="203.0.113.1",
        wan_interface=PortDiagnostics(
            port_id=1,
            port_name="wan1",
            link_speed_mbps=1000,
            stp_state="unknown",
            oper_status="up",
            admin_status="up",
            is_uplink=True,
            neighbor_name="ISP Gateway",
            neighbor_ip="203.0.113.1",
        ),
        lan_interface=PortDiagnostics(
            port_id=2,
            port_name="lan",
            link_speed_mbps=1000,
            stp_state="unknown",
            oper_status="up",
            admin_status="up",
            is_downlink=True,
            neighbor_name="Core-SW1",
            neighbor_ip="10.0.0.2",
            neighbor_port="Gi0/1",
        ),
        ports=[
            PortDiagnostics(
                port_id=1,
                port_name="wan1",
                link_speed_mbps=1000,
                stp_state="unknown",
                oper_status="up",
                admin_status="up",
                is_uplink=True,
                neighbor_name="ISP Gateway",
                neighbor_ip="203.0.113.1",
            ),
            PortDiagnostics(
                port_id=2,
                port_name="lan",
                link_speed_mbps=1000,
                stp_state="unknown",
                oper_status="up",
                admin_status="up",
                is_downlink=True,
                neighbor_name="Core-SW1",
                neighbor_ip="10.0.0.2",
                neighbor_port="Gi0/1",
            ),
            PortDiagnostics(
                port_id=3,
                port_name="dmz",
                link_speed_mbps=None,
                stp_state="unknown",
                oper_status="down",
                admin_status="down",
            ),
            PortDiagnostics(
                port_id=4,
                port_name="ssl.root",
                link_speed_mbps=None,
                stp_state="unknown",
                oper_status="up",
                admin_status="up",
            ),
        ],
        uplink_port=PortDiagnostics(
            port_id=1,
            port_name="wan1",
            link_speed_mbps=1000,
            stp_state="unknown",
            oper_status="up",
            admin_status="up",
            is_uplink=True,
            neighbor_name="ISP Gateway",
            neighbor_ip="203.0.113.1",
        ),
        downlink_port=PortDiagnostics(
            port_id=2,
            port_name="lan",
            link_speed_mbps=1000,
            stp_state="unknown",
            oper_status="up",
            admin_status="up",
            is_downlink=True,
            neighbor_name="Core-SW1",
            neighbor_ip="10.0.0.2",
            neighbor_port="Gi0/1",
        ),
    ),
]


# UniFi Switch without STP BRIDGE-MIB (Variant A: upstream gateway via LLDP)
UNIFI_DEMO_MIB_WITH_UPSTREAM: dict[str, any] = {
    OID_SYS_DESCR: "UniFi Switch USW-Lite-16-PoE, Linux 4.14.222-ui-5.2",
    OID_SYS_NAME: "USW-Lite-16-PoE",
    OID_SYS_OBJECT_ID: "1.3.6.1.4.1.41112.1.4",
    OID_DOT1D_BASE_BRIDGE_ADDRESS: bytes.fromhex("7483c2112233"),
    f"{OID_IF_NAME}.1": "Port 1",
    f"{OID_IF_HIGH_SPEED}.1": 1000,
    f"{OID_LLDP_REM_SYS_NAME}.0.1.1": "Local-Host",
    f"{OID_LLDP_REM_PORT_ID}.0.1.1": "eth0",
    f"{OID_IF_NAME}.16": "Port 16",
    f"{OID_IF_HIGH_SPEED}.16": 1000,
    f"{OID_LLDP_REM_SYS_NAME}.0.16.1": "UDM-Pro",
    f"{OID_LLDP_REM_PORT_ID}.0.16.1": "Port 9",
    f"{OID_LLDP_REM_MAN_ADDR_TABLE}.3.0.16.1.1.4.192.168.1.1": 1,
}

# Upstream UniFi Gateway / Router MIB
UNIFI_GATEWAY_DEMO_MIB: dict[str, any] = {
    OID_SYS_DESCR: "UniFi Dream Machine Pro Gateway, Linux 5.4.0-ui-alp",
    OID_SYS_NAME: "UDM-Pro",
    OID_SYS_OBJECT_ID: "1.3.6.1.4.1.41112.1.1",
    OID_IP_ROUTE_NEXT_HOP_DEFAULT: "198.51.100.1",
    OID_IP_ROUTE_IF_INDEX_DEFAULT: 9,
    f"{OID_IF_NAME}.8": "lan",
    f"{OID_IF_HIGH_SPEED}.8": 1000,
    f"{OID_IF_OPER_STATUS}.8": 1,
    f"{OID_IF_ADMIN_STATUS}.8": 1,
    f"{OID_IF_NAME}.9": "wan1",
    f"{OID_IF_HIGH_SPEED}.9": 1000,
    f"{OID_IF_OPER_STATUS}.9": 1,
    f"{OID_IF_ADMIN_STATUS}.9": 1,
    f"{OID_IP_NET_TO_MEDIA_TABLE}.1.8.192.168.1.20": 8,
    f"{OID_IP_NET_TO_MEDIA_TABLE}.3.8.192.168.1.20": "192.168.1.20",
}

# UniFi Switch without STP BRIDGE-MIB (Variant B: no upstream LLDP neighbor)
UNIFI_DEMO_MIB_NO_UPSTREAM: dict[str, any] = {
    OID_SYS_DESCR: "UniFi Switch USW-Lite-16-PoE, Linux 4.14.222-ui-5.2",
    OID_SYS_NAME: "USW-Lite-16-PoE",
    OID_SYS_OBJECT_ID: "1.3.6.1.4.1.41112.1.4",
    OID_DOT1D_BASE_BRIDGE_ADDRESS: bytes.fromhex("7483c2112233"),
    f"{OID_IF_NAME}.1": "Port 1",
    f"{OID_IF_HIGH_SPEED}.1": 1000,
    f"{OID_LLDP_REM_SYS_NAME}.0.1.1": "Local-Host",
    f"{OID_LLDP_REM_PORT_ID}.0.1.1": "eth0",
}

# Aruba 2930F Switch MIB (port 3 has untagged VLAN 1 and tagged VLAN 30)
# Static table has configured untagged membership for VLAN 1;
# Current tables carry operational membership for VLAN 1 and tagged VLAN 30.
ARUBA_DEMO_MIB: dict[str, any] = {
    OID_SYS_DESCR: "Aruba 2930F-24G-4SFP+ Switch (JL259A), WC.16.10.0016",
    OID_SYS_NAME: "Aruba-2930F",
    OID_SYS_OBJECT_ID: "1.3.6.1.4.1.11.2.3.7.11.162",
    OID_DOT1D_BASE_BRIDGE_ADDRESS: bytes.fromhex("000b86112233"),
    OID_DOT1D_STP_ROOT_BRIDGE: bytes.fromhex("000b86112233"),
    OID_DOT1D_STP_ROOT_PORT: 0,
    f"{OID_DOT1D_BASE_PORT_IFINDEX}.3": 3,
    f"{OID_IF_NAME}.3": "Port 3",
    f"{OID_IF_HIGH_SPEED}.3": 1000,
    f"{OID_DOT1D_STP_PORT_STATE}.3": 5,
    f"{OID_DOT1Q_PVID}.3": 1,
    # Static table: configured membership for VLAN 1 (port 3 is bit 2: 0x20)
    f"{OID_DOT1Q_VLAN_STATIC_EGRESS_PORTS}.1": bytes([0x20]),
    f"{OID_DOT1Q_VLAN_STATIC_UNTAGGED_PORTS}.1": bytes([0x20]),
    # Current table: operational membership for VLAN 1 and tagged VLAN 30
    f"{OID_DOT1Q_VLAN_CURRENT_EGRESS_PORTS}.0.1": bytes([0x20]),
    f"{OID_DOT1Q_VLAN_CURRENT_EGRESS_PORTS}.0.30": bytes([0x20]),
    f"{OID_DOT1Q_VLAN_CURRENT_UNTAGGED_PORTS}.0.1": bytes([0x20]),
    OID_IP_ROUTE_NEXT_HOP_DEFAULT: "10.0.0.1",
}

# Aruba switch MIB fixture variant: ONLY current tables carry membership (simulating sparse static)
ARUBA_DEMO_MIB_CURRENT_ONLY: dict[str, any] = {
    OID_SYS_DESCR: "Aruba 2930F-24G-4SFP+ Switch (JL259A), WC.16.10.0016",
    OID_SYS_NAME: "Aruba-2930F",
    OID_SYS_OBJECT_ID: "1.3.6.1.4.1.11.2.3.7.11.162",
    OID_DOT1D_BASE_BRIDGE_ADDRESS: bytes.fromhex("000b86112233"),
    OID_DOT1D_STP_ROOT_BRIDGE: bytes.fromhex("000b86112233"),
    OID_DOT1D_STP_ROOT_PORT: 0,
    f"{OID_DOT1D_BASE_PORT_IFINDEX}.3": 3,
    f"{OID_IF_NAME}.3": "Port 3",
    f"{OID_IF_HIGH_SPEED}.3": 1000,
    f"{OID_DOT1D_STP_PORT_STATE}.3": 5,
    f"{OID_DOT1Q_PVID}.3": 1,
    # Static tables completely absent (current-only membership)
    f"{OID_DOT1Q_VLAN_CURRENT_EGRESS_PORTS}.0.1": bytes([0x20]),
    f"{OID_DOT1Q_VLAN_CURRENT_EGRESS_PORTS}.0.30": bytes([0x20]),
    f"{OID_DOT1Q_VLAN_CURRENT_UNTAGGED_PORTS}.0.1": bytes([0x20]),
    OID_IP_ROUTE_NEXT_HOP_DEFAULT: "10.0.0.1",
}

UNIFI_DEMO_HOPS_WITH_UPSTREAM: list[Hop] = [
    Hop(
        hop_index=1,
        hostname="USW-Lite-16-PoE",
        mgmt_ip="192.168.1.20",
        sys_descr="UniFi Switch USW-Lite-16-PoE, Linux 4.14.222-ui-5.2",
        platform="Ubiquiti USW-Lite-16-PoE",
        device_type="switch",
        is_stp_root=False,
        stp_bridge_id="74:83:c2:11:22:33",
        status="ok",
        response_time_ms=3.1,
        ports=[
            PortDiagnostics(
                port_id=1,
                port_name="Port 1",
                stp_state="unknown",
                link_speed_mbps=1000,
                is_downlink=True,
                neighbor_name="Local-Host",
                neighbor_port="eth0",
            ),
            PortDiagnostics(
                port_id=16,
                port_name="Port 16",
                stp_state="unknown",
                link_speed_mbps=1000,
                is_uplink=True,
                neighbor_name="UDM-Pro",
                neighbor_ip="192.168.1.1",
                neighbor_port="Port 9",
            ),
        ],
        uplink_port=PortDiagnostics(
            port_id=16,
            port_name="Port 16",
            stp_state="unknown",
            link_speed_mbps=1000,
            is_uplink=True,
            neighbor_name="UDM-Pro",
            neighbor_ip="192.168.1.1",
            neighbor_port="Port 9",
        ),
        downlink_port=PortDiagnostics(
            port_id=1,
            port_name="Port 1",
            stp_state="unknown",
            link_speed_mbps=1000,
            is_downlink=True,
            neighbor_name="Local-Host",
            neighbor_port="eth0",
        ),
    ),
    Hop(
        hop_index=2,
        hostname="UDM-Pro",
        mgmt_ip="192.168.1.1",
        sys_descr="UniFi Dream Machine Pro Gateway, Linux 5.4.0-ui-alp",
        platform="Ubiquiti UniFi Dream Machine Pro",
        device_type="router",
        is_stp_root=False,
        default_gateway="198.51.100.1",
        status="router_reached",
        response_time_ms=2.4,
        isp_gateway="198.51.100.1",
        wan_interface=PortDiagnostics(
            port_id=9,
            port_name="wan1",
            link_speed_mbps=1000,
            oper_status="up",
            admin_status="up",
            is_uplink=True,
            neighbor_name="ISP Gateway",
            neighbor_ip="198.51.100.1",
        ),
        lan_interface=PortDiagnostics(
            port_id=8,
            port_name="lan",
            link_speed_mbps=1000,
            oper_status="up",
            admin_status="up",
            is_downlink=True,
            neighbor_name="USW-Lite-16-PoE",
            neighbor_ip="192.168.1.20",
            neighbor_port="Port 16",
        ),
        ports=[
            PortDiagnostics(
                port_id=8,
                port_name="lan",
                link_speed_mbps=1000,
                oper_status="up",
                admin_status="up",
                is_downlink=True,
                neighbor_name="USW-Lite-16-PoE",
                neighbor_ip="192.168.1.20",
                neighbor_port="Port 16",
            ),
            PortDiagnostics(
                port_id=9,
                port_name="wan1",
                link_speed_mbps=1000,
                oper_status="up",
                admin_status="up",
                is_uplink=True,
                neighbor_name="ISP Gateway",
                neighbor_ip="198.51.100.1",
            ),
        ],
        uplink_port=PortDiagnostics(
            port_id=9,
            port_name="wan1",
            link_speed_mbps=1000,
            oper_status="up",
            admin_status="up",
            is_uplink=True,
            neighbor_name="ISP Gateway",
            neighbor_ip="198.51.100.1",
        ),
        downlink_port=PortDiagnostics(
            port_id=8,
            port_name="lan",
            link_speed_mbps=1000,
            oper_status="up",
            admin_status="up",
            is_downlink=True,
            neighbor_name="USW-Lite-16-PoE",
            neighbor_ip="192.168.1.20",
            neighbor_port="Port 16",
        ),
    ),
]

UNIFI_DEMO_HOPS_NO_UPSTREAM: list[Hop] = [
    Hop(
        hop_index=1,
        hostname="USW-Lite-16-PoE",
        mgmt_ip="192.168.1.20",
        sys_descr="UniFi Switch USW-Lite-16-PoE, Linux 4.14.222-ui-5.2",
        platform="Ubiquiti USW-Lite-16-PoE",
        device_type="switch",
        is_stp_root=False,
        stp_bridge_id="74:83:c2:11:22:33",
        status="no_upstream",
        response_time_ms=3.1,
        ports=[
            PortDiagnostics(
                port_id=1,
                port_name="Port 1",
                stp_state="unknown",
                link_speed_mbps=1000,
                is_downlink=True,
                neighbor_name="Local-Host",
                neighbor_port="eth0",
            ),
        ],
        uplink_port=None,
        downlink_port=PortDiagnostics(
            port_id=1,
            port_name="Port 1",
            stp_state="unknown",
            link_speed_mbps=1000,
            is_downlink=True,
            neighbor_name="Local-Host",
            neighbor_port="eth0",
        ),
    ),
]


UNIFI_DEMO_HOPS_AMBIGUOUS: list[Hop] = [
    Hop(
        hop_index=1,
        hostname="USW-Lite-16-PoE",
        mgmt_ip="192.168.1.20",
        sys_descr="UniFi Switch USW-Lite-16-PoE, Linux 4.14.222-ui-5.2",
        platform="Ubiquiti USW-Lite-16-PoE",
        device_type="switch",
        is_stp_root=False,
        stp_bridge_id="74:83:c2:11:22:33",
        status="ambiguous",
        response_time_ms=3.1,
        ports=[
            PortDiagnostics(
                port_id=1,
                port_name="Port 1",
                pvid=1,
                allowed_vlans=[1, 10, 20],
                stp_state="forwarding",
                link_speed_mbps=1000,
                is_downlink=True,
                neighbor_name="Local-Host",
                neighbor_port="eth0",
            ),
            PortDiagnostics(
                port_id=15,
                port_name="Port 15",
                pvid=1,
                allowed_vlans=[1, 10, 20],
                stp_state="unknown",
                link_speed_mbps=1000,
                neighbor_name="Aruba-2930F",
                neighbor_ip="10.0.0.10",
                neighbor_port="1/1",
            ),
            PortDiagnostics(
                port_id=16,
                port_name="Port 16",
                pvid=1,
                allowed_vlans=[1],
                stp_state="unknown",
                link_speed_mbps=1000,
                neighbor_name="U6-Pro-AP",
                neighbor_ip="192.168.1.50",
                neighbor_port="eth0",
            ),
        ],
        uplink_port=None,
        downlink_port=PortDiagnostics(
            port_id=1,
            port_name="Port 1",
            pvid=1,
            allowed_vlans=[1, 10, 20],
            stp_state="forwarding",
            link_speed_mbps=1000,
            is_downlink=True,
            neighbor_name="Local-Host",
            neighbor_port="eth0",
        ),
        ambiguous_candidates=[
            PortDiagnostics(
                port_id=15,
                port_name="Port 15",
                pvid=1,
                allowed_vlans=[1, 10, 20],
                stp_state="unknown",
                link_speed_mbps=1000,
                neighbor_name="Aruba-2930F",
                neighbor_ip="10.0.0.10",
                neighbor_port="1/1",
            ),
            PortDiagnostics(
                port_id=16,
                port_name="Port 16",
                pvid=1,
                allowed_vlans=[1],
                stp_state="unknown",
                link_speed_mbps=1000,
                neighbor_name="U6-Pro-AP",
                neighbor_ip="192.168.1.50",
                neighbor_port="eth0",
            ),
        ],
    ),
]


def get_unifi_demo_path(
    variant: str = "with_upstream",
    start_ip: str = "192.168.1.20",
    forced_next_ip: str | None = None,
) -> UpstreamPath:
    """Return a canned demo upstream path for a UniFi switch."""
    if variant == "no_upstream":
        return UpstreamPath(
            start_ip=start_ip,
            hops=UNIFI_DEMO_HOPS_NO_UPSTREAM,
            edge_type="no_upstream",
            edge_summary=f"No upstream neighbor visible from USW-Lite-16-PoE ({start_ip}) via LLDP — this switch appears to be the network edge.",
            success=True,
        )
    if variant == "ambiguous" and not forced_next_ip:
        return UpstreamPath(
            start_ip=start_ip,
            hops=UNIFI_DEMO_HOPS_AMBIGUOUS,
            edge_type="ambiguous",
            edge_summary=(
                f"Walk stopped at hop 1 (USW-Lite-16-PoE): "
                f"multiple upstream LLDP candidate neighbors found (Aruba-2930F (10.0.0.10), U6-Pro-AP (192.168.1.50)) — "
                f"verify upstream topology."
            ),
            success=False,
        )
    if forced_next_ip == "10.0.0.10":
        aruba_port_down = PortDiagnostics(
            port_id=3,
            port_name="Port 3",
            pvid=1,
            allowed_vlans=[1, 30],
            tagged_vlans=[30],
            untagged_vlans=[1],
            stp_state="forwarding",
            link_speed_mbps=1000,
            is_downlink=True,
            neighbor_name="USW-Lite-16-PoE",
            neighbor_ip=start_ip,
            neighbor_port="Port 15",
        )
        hop1 = Hop(
            hop_index=1,
            hostname="USW-Lite-16-PoE",
            mgmt_ip=start_ip,
            sys_descr="UniFi Switch USW-Lite-16-PoE, Linux 4.14.222-ui-5.2",
            platform="Ubiquiti USW-Lite-16-PoE",
            device_type="switch",
            is_stp_root=False,
            stp_bridge_id="74:83:c2:11:22:33",
            status="ok",
            response_time_ms=3.1,
            ports=UNIFI_DEMO_HOPS_AMBIGUOUS[0].ports,
            downlink_port=UNIFI_DEMO_HOPS_AMBIGUOUS[0].downlink_port,
            uplink_port=PortDiagnostics(
                port_id=15,
                port_name="Port 15",
                pvid=1,
                allowed_vlans=[1, 10, 20],
                stp_state="forwarding",
                link_speed_mbps=1000,
                is_uplink=True,
                neighbor_name="Aruba-2930F",
                neighbor_ip="10.0.0.10",
                neighbor_port="Port 3",
            ),
            ambiguous_candidates=UNIFI_DEMO_HOPS_AMBIGUOUS[0].ambiguous_candidates,
        )
        hop2 = Hop(
            hop_index=2,
            hostname="Aruba-2930F",
            mgmt_ip="10.0.0.10",
            sys_descr="Aruba 2930F-24G-4SFP+ Switch (JL259A), WC.16.10.0016",
            platform="Aruba 2930F",
            device_type="switch",
            is_stp_root=True,
            stp_root_bridge_id="32768 / 00:0b:86:11:22:33",
            stp_bridge_id="32768 / 00:0b:86:11:22:33",
            default_gateway="10.0.0.1",
            status="root_reached",
            response_time_ms=2.8,
            ports=[aruba_port_down],
            downlink_port=aruba_port_down,
        )
        return UpstreamPath(
            start_ip=start_ip,
            hops=[hop1, hop2],
            edge_type="stp_root",
            edge_summary="L2 STP Root reached: Aruba-2930F (10.0.0.10), Gateway: 10.0.0.1",
            success=True,
        )
    if forced_next_ip == "192.168.1.50":
        ap_port_down = PortDiagnostics(
            port_id="eth0",
            port_name="eth0",
            pvid=1,
            allowed_vlans=[1],
            stp_state="unknown",
            link_speed_mbps=1000,
            is_downlink=True,
            neighbor_name="USW-Lite-16-PoE",
            neighbor_ip=start_ip,
            neighbor_port="Port 16",
        )
        hop1 = Hop(
            hop_index=1,
            hostname="USW-Lite-16-PoE",
            mgmt_ip=start_ip,
            sys_descr="UniFi Switch USW-Lite-16-PoE, Linux 4.14.222-ui-5.2",
            platform="Ubiquiti USW-Lite-16-PoE",
            device_type="switch",
            is_stp_root=False,
            stp_bridge_id="74:83:c2:11:22:33",
            status="ok",
            response_time_ms=3.1,
            ports=UNIFI_DEMO_HOPS_AMBIGUOUS[0].ports,
            downlink_port=UNIFI_DEMO_HOPS_AMBIGUOUS[0].downlink_port,
            uplink_port=PortDiagnostics(
                port_id=16,
                port_name="Port 16",
                pvid=1,
                allowed_vlans=[1],
                stp_state="unknown",
                link_speed_mbps=1000,
                is_uplink=True,
                neighbor_name="U6-Pro-AP",
                neighbor_ip="192.168.1.50",
                neighbor_port="eth0",
            ),
            ambiguous_candidates=UNIFI_DEMO_HOPS_AMBIGUOUS[0].ambiguous_candidates,
        )
        hop2 = Hop(
            hop_index=2,
            hostname="U6-Pro-AP",
            mgmt_ip="192.168.1.50",
            sys_descr="Ubiquiti UniFi 6 Pro Access Point",
            platform="Ubiquiti U6-Pro",
            device_type="unknown",
            is_stp_root=False,
            status="no_upstream",
            response_time_ms=2.1,
            ports=[ap_port_down],
            downlink_port=ap_port_down,
        )
        return UpstreamPath(
            start_ip=start_ip,
            hops=[hop1, hop2],
            edge_type="no_upstream",
            edge_summary="No upstream neighbor visible from U6-Pro-AP (192.168.1.50) via LLDP — this switch appears to be the network edge.",
            success=True,
        )
    return UpstreamPath(
        start_ip=start_ip,
        hops=UNIFI_DEMO_HOPS_WITH_UPSTREAM,
        edge_type="router",
        edge_summary="Edge router reached: UDM-Pro (192.168.1.1) — WAN wan1 via ISP gateway 198.51.100.1",
        success=True,
    )


ARUBA_DEMO_HOPS: list[Hop] = [
    Hop(
        hop_index=1,
        hostname="Aruba-2930F",
        mgmt_ip="10.0.0.10",
        sys_descr="Aruba 2930F-24G-4SFP+ Switch (JL259A), WC.16.10.0016",
        platform="Aruba 2930F",
        device_type="switch",
        is_stp_root=True,
        stp_root_bridge_id="32768 / 00:0b:86:11:22:33",
        stp_bridge_id="32768 / 00:0b:86:11:22:33",
        default_gateway="10.0.0.1",
        status="root_reached",
        response_time_ms=2.8,
        ports=[
            PortDiagnostics(
                port_id=3,
                port_name="Port 3",
                pvid=1,
                allowed_vlans=[1, 30],
                tagged_vlans=[30],
                untagged_vlans=[1],
                stp_state="forwarding",
                link_speed_mbps=1000,
                is_downlink=True,
                neighbor_name="Local-Host",
                neighbor_ip="10.0.0.42",
                neighbor_port="eth0",
            ),
        ],
        downlink_port=PortDiagnostics(
            port_id=3,
            port_name="Port 3",
            pvid=1,
            allowed_vlans=[1, 30],
            tagged_vlans=[30],
            untagged_vlans=[1],
            stp_state="forwarding",
            link_speed_mbps=1000,
            is_downlink=True,
            neighbor_name="Local-Host",
            neighbor_ip="10.0.0.42",
            neighbor_port="eth0",
        ),
    ),
]


def get_aruba_demo_path(start_ip: str = "10.0.0.10") -> UpstreamPath:
    """Return a canned demo upstream path for an Aruba switch."""
    return UpstreamPath(
        start_ip=start_ip,
        hops=ARUBA_DEMO_HOPS,
        edge_type="stp_root",
        edge_summary="L2 STP Root reached: Aruba-2930F (10.0.0.10), Gateway: 10.0.0.1",
        success=True,
    )


def get_demo_path(start_ip: str = "10.0.0.3", forced_next_ip: str | None = None) -> UpstreamPath:
    """Return a canned demo upstream path."""
    if start_ip == "10.0.0.10":
        return get_aruba_demo_path(start_ip=start_ip)
    if start_ip == "192.168.1.20":
        variant = "ambiguous" if not forced_next_ip else "with_upstream"
        return get_unifi_demo_path(variant=variant, start_ip=start_ip, forced_next_ip=forced_next_ip)
    return UpstreamPath(
        start_ip=start_ip,
        hops=DEMO_HOPS,
        edge_type="firewall",
        edge_summary="Edge firewall reached: FW-Edge01 (10.0.0.1) — WAN wan1 via ISP gateway 203.0.113.1",
        success=True,
    )
